services:
  frontend:
    image: nginx-frontend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    depends_on:
      - backend
    environment:
      - BACKEND_PORT=3000
    ports:
      - "80:80"
    networks:
      - app

  backend:
    image: express-backend
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: ./src/backend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app
      - supabase_network_cardgamesimulator

networks:
  app:
  supabase_network_cardgamesimulator:
    external: true
